services:
    user-database:
        image: postgres:16
        environment:
            POSTGRES_DB: ${USER_CRUD_DB}
            POSTGRES_USER: ${USER_CRUD_USER}
            POSTGRES_PASSWORD: ${USER_CRUD_PASSWORD}
        ports:
            - "${USER_CRUD_PORT}:5432"
        volumes:
            - user_data:/var/lib/postgresql/data
            - ./services/user_database/sql/schema:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - user-db-net

    file-storage:
        build:
            context: .
            dockerfile: services/file_storage/Dockerfile
        ports:
            - "8000:8000"
        environment:
            LISTEN_ADDR: ${FILE_STORAGE_LISTEN_ADDR}
            DATA_LOCATION: ${FILE_STORAGE_DATA_LOCATION}
        volumes:
            - file_storage_data:/data
        networks:
            - file-storage-net

    hashicorp-vault-dev:
        image: hashicorp/vault
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: "root"
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        ports:
            - "8200:8200"
        networks:
            - vault-net

    user-database-crud:
        build:
            context: .
            dockerfile: services/user_database/Dockerfile
        ports:
            - "8080:8080"
        environment:
            USER_CRUD_CONNECTION_STRING: ${USER_CRUD_CONNECTION_STRING}
            USER_CRUD_JWT_PROVIDER_NAME: ${USER_CRUD_JWT_PROVIDER_NAME}
            JWT_STORE_PATH: ${JWT_STORE_PATH}
            JWT_SUBJECT_NORMAL: ${JWT_SUBJECT_NORMAL}
            JWT_TIME_IN_M_NORMAL: ${JWT_TIME_IN_M_NORMAL}
            JWT_SUBJECT_REFRESH: ${JWT_SUBJECT_REFRESH}
            JWT_TIME_IN_D_REFRESH: ${JWT_TIME_IN_D_REFRESH}
            VAULT_ADDR: http://hashicorp-vault-dev:8200
            VAULT_TOKEN: root
        depends_on:
            user-database:
                condition: service_healthy
            hashicorp-vault-dev:
                condition: service_started
        networks:
            - user-db-net
            - general
            - vault-net

    clickhouse-database:
        image: clickhouse/clickhouse-server:latest
        ports:
            - "${CLICKHOUSE_PORT_TCP}:9000"
            - "${CLICKHOUSE_PORT_HTTP}:8123"
        environment:
          CLICKHOUSE_DB: ${CLICKHOUSE_DB}
          CLICKHOUSE_USER: ${CLICKHOUSE_USER}
          CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
        volumes:
            - clickhouse_data:/var/lib/clickhouse/
            - clickhouse_logs:/var/log/clickhouse-server/
            - ./services/data_warehouse:/docker-entrypoint-initdb.d
        networks:
            - clickhouse-net

    bandit-database:
        image: postgres:16
        environment:
            POSTGRES_DB: ${BANDIT_DB}
            POSTGRES_USER: ${BANDIT_USER}
            POSTGRES_PASSWORD: ${BANDIT_PASSWORD}
        ports:
            - "${BANDIT_PORT}:5432"
        volumes:
            - bandit_data:/var/lib/postgresql/data
            - ./services/bandit_system/src/sql:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - bandit-db-net

    bandit-system:
        build:
            context: services/bandit_system
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        environment:
            DB_CONNECTION_STRING_WAREHOUSE: ${CLICKHOUSE_CONNECTION_STRING}
            WAREHOUSE_BANDIT_DATA_TABLE: ${WAREHOUSE_BANDIT_DATA_TABLE}
            DB_CONNECTION_STRING_PARAMS: ${BANDIT_CONNECTION_STRING}
            BANDIT_DATA_TABLE: ${BANDIT_DATA_TABLE}
            BANDIT_ALPHA: ${BANDIT_ALPHA}
            BANDIT_RIDGE_LAMBDA: ${BANDIT_RIDGE_LAMBDA}
            SHERMAN_MORRISON_RECOMPUTE_INTERVAL: ${SHERMAN_MORRISON_RECOMPUTE_INTERVAL}
            SHERMAN_MORRISON_DIVERGENCE_THRESHOLD: ${SHERMAN_MORRISON_DIVERGENCE_THRESHOLD}
        depends_on:
            bandit-database:
                condition: service_healthy
            clickhouse-database:
                condition: service_started
        networks:
            - bandit-db-net
            - clickhouse-net
            - general


volumes:
    user_data:
    clickhouse_data:
    clickhouse_logs:
    file_storage_data:
    bandit_data:

networks:
    clickhouse-net:
    user-db-net:
    file-storage-net:
    vault-net:
    bandit-db-net:
    general:

