// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 00_user.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, hashed_password, bio, profile_image_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING uuid
`

type CreateUserParams struct {
	Username         string      `json:"username"`
	Email            string      `json:"email"`
	HashedPassword   string      `json:"hashed_password"`
	Bio              pgtype.Text `json:"bio"`
	ProfileImagePath pgtype.Text `json:"profile_image_path"`
}

// ---- PUT
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Bio,
		arg.ProfileImagePath,
	)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getHashPassword = `-- name: GetHashPassword :one
SELECT hashed_password FROM users
WHERE uuid = $1
`

func (q *Queries) GetHashPassword(ctx context.Context, uuid pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHashPassword, uuid)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const getPublicUser = `-- name: GetPublicUser :one
SELECT uuid, username, email, bio, profile_image_path, created_at, updated_at FROM public_user
WHERE uuid = $1 LIMIT 1
`

// ------------- Users -----------------
// ---- GET
func (q *Queries) GetPublicUser(ctx context.Context, uuid pgtype.UUID) (PublicUser, error) {
	row := q.db.QueryRow(ctx, getPublicUser, uuid)
	var i PublicUser
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, username, email, hashed_password, bio, profile_image_path, created_at, updated_at
FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchForUser = `-- name: SearchForUser :many
SELECT
    pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at,
    similarity(pu.username, $1)::float AS similarity_score
FROM public_user pu
WHERE pu.username % $1
AND (
    $3 < 0
    OR (
        similarity(pu.username, $1) < $3
        OR (similarity(pu.username, $1) = $3 AND pu.created_at < $4)
    )
)
ORDER BY similarity(pu.username, $1) DESC, pu.created_at DESC
LIMIT $2
`

type SearchForUserParams struct {
	Similarity interface{}      `json:"similarity"`
	Limit      int32            `json:"limit"`
	Column3    interface{}      `json:"column_3"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type SearchForUserRow struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	SimilarityScore  float64          `json:"similarity_score"`
}

func (q *Queries) SearchForUser(ctx context.Context, arg SearchForUserParams) ([]SearchForUserRow, error) {
	rows, err := q.db.Query(ctx, searchForUser,
		arg.Similarity,
		arg.Limit,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchForUserRow
	for rows.Next() {
		var i SearchForUserRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SimilarityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users
SET email = $2
WHERE uuid = $1
`

type UpdateEmailParams struct {
	Uuid  pgtype.UUID `json:"uuid"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.Uuid, arg.Email)
	return err
}

const updateImage = `-- name: UpdateImage :exec
UPDATE users
SET profile_image_path = $2
WHERE uuid = $1
`

type UpdateImageParams struct {
	Uuid             pgtype.UUID `json:"uuid"`
	ProfileImagePath pgtype.Text `json:"profile_image_path"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.Exec(ctx, updateImage, arg.Uuid, arg.ProfileImagePath)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET hashed_password = $2
WHERE uuid = $1
`

type UpdatePasswordParams struct {
	Uuid           pgtype.UUID `json:"uuid"`
	HashedPassword string      `json:"hashed_password"`
}

// ---- POST
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Uuid, arg.HashedPassword)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users
SET username = $2,
    bio = $3
WHERE uuid = $1
`

type UpdateProfileParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	Username string      `json:"username"`
	Bio      pgtype.Text `json:"bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.Uuid, arg.Username, arg.Bio)
	return err
}
