// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 01_artist.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToArtist = `-- name: AddUserToArtist :exec
INSERT INTO artist_member (artist_uuid, user_uuid, role)
VALUES ($1, $2, $3)
`

type AddUserToArtistParams struct {
	ArtistUuid pgtype.UUID      `json:"artist_uuid"`
	UserUuid   pgtype.UUID      `json:"user_uuid"`
	Role       ArtistMemberRole `json:"role"`
}

// ---- PUT
func (q *Queries) AddUserToArtist(ctx context.Context, arg AddUserToArtistParams) error {
	_, err := q.db.Exec(ctx, addUserToArtist, arg.ArtistUuid, arg.UserUuid, arg.Role)
	return err
}

const changeUserRole = `-- name: ChangeUserRole :exec
UPDATE artist_member
SET role = $3
WHERE artist_uuid = $1 AND user_uuid = $2
`

type ChangeUserRoleParams struct {
	ArtistUuid pgtype.UUID      `json:"artist_uuid"`
	UserUuid   pgtype.UUID      `json:"user_uuid"`
	Role       ArtistMemberRole `json:"role"`
}

// ---- POST
func (q *Queries) ChangeUserRole(ctx context.Context, arg ChangeUserRoleParams) error {
	_, err := q.db.Exec(ctx, changeUserRole, arg.ArtistUuid, arg.UserUuid, arg.Role)
	return err
}

const createArtist = `-- name: CreateArtist :exec
WITH new_artist as (
    INSERT INTO artist (artist_name, bio, profile_image_path)
    VALUES ($2, $3, $4)
    RETURNING uuid
)
INSERT INTO artist_member (artist_uuid, user_uuid, "role")
SELECT uuid, $1, 'owner'
FROM new_artist
`

type CreateArtistParams struct {
	UserUuid         pgtype.UUID `json:"user_uuid"`
	ArtistName       string      `json:"artist_name"`
	Bio              pgtype.Text `json:"bio"`
	ProfileImagePath pgtype.Text `json:"profile_image_path"`
}

// ---- PUT
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) error {
	_, err := q.db.Exec(ctx, createArtist,
		arg.UserUuid,
		arg.ArtistName,
		arg.Bio,
		arg.ProfileImagePath,
	)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT uuid, artist_name, bio, profile_image_path, created_at, updated_at FROM artist
WHERE uuid = $1
`

// ------------- Artists -----------------
// ---- GET
func (q *Queries) GetArtist(ctx context.Context, uuid pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, uuid)
	var i Artist
	err := row.Scan(
		&i.Uuid,
		&i.ArtistName,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistForUser = `-- name: GetArtistForUser :many
SELECT art.uuid, art.artist_name, art.bio, art.profile_image_path, art.created_at, art.updated_at, am.role, am.joined_at
FROM artist_member am
         JOIN artist art
              ON am.artist_uuid = art.uuid
WHERE am.user_uuid = $1
`

type GetArtistForUserRow struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	ArtistName       string           `json:"artist_name"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Role             ArtistMemberRole `json:"role"`
	JoinedAt         pgtype.Timestamp `json:"joined_at"`
}

func (q *Queries) GetArtistForUser(ctx context.Context, userUuid pgtype.UUID) ([]GetArtistForUserRow, error) {
	rows, err := q.db.Query(ctx, getArtistForUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistForUserRow
	for rows.Next() {
		var i GetArtistForUserRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistsAlphabetically = `-- name: GetArtistsAlphabetically :many
SELECT uuid, artist_name, bio, profile_image_path, created_at, updated_at FROM artist
WHERE (
    $3::timestamptz IS NULL
    OR (
        artist_name > $2
        OR (artist_name = $2 AND created_at > $3)
    )
)
ORDER BY artist_name, created_at
LIMIT $1
`

type GetArtistsAlphabeticallyParams struct {
	Limit      int32              `json:"limit"`
	ArtistName string             `json:"artist_name"`
	Column3    pgtype.Timestamptz `json:"column_3"`
}

func (q *Queries) GetArtistsAlphabetically(ctx context.Context, arg GetArtistsAlphabeticallyParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistsAlphabetically, arg.Limit, arg.ArtistName, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersRepresentingArtist = `-- name: GetUsersRepresentingArtist :many

SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at, am.role, am.joined_at
FROM artist_member am
         JOIN public_user pu
              ON am.user_uuid = pu.uuid
WHERE am.artist_uuid = $1
`

type GetUsersRepresentingArtistRow struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Role             ArtistMemberRole `json:"role"`
	JoinedAt         pgtype.Timestamp `json:"joined_at"`
}

// ---- DELETE
// deletes are overrated
// ------------- ArtistMember -----------------
// ---- GET
func (q *Queries) GetUsersRepresentingArtist(ctx context.Context, artistUuid pgtype.UUID) ([]GetUsersRepresentingArtistRow, error) {
	rows, err := q.db.Query(ctx, getUsersRepresentingArtist, artistUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRepresentingArtistRow
	for rows.Next() {
		var i GetUsersRepresentingArtistRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromArtist = `-- name: RemoveUserFromArtist :exec
DELETE FROM artist_member
WHERE artist_uuid = $1 AND user_uuid = $2
`

type RemoveUserFromArtistParams struct {
	ArtistUuid pgtype.UUID `json:"artist_uuid"`
	UserUuid   pgtype.UUID `json:"user_uuid"`
}

// ---- DELETE
func (q *Queries) RemoveUserFromArtist(ctx context.Context, arg RemoveUserFromArtistParams) error {
	_, err := q.db.Exec(ctx, removeUserFromArtist, arg.ArtistUuid, arg.UserUuid)
	return err
}

const searchForArtist = `-- name: SearchForArtist :many
SELECT
    a.uuid, a.artist_name, a.bio, a.profile_image_path, a.created_at, a.updated_at,
    similarity(a.artist_name, $1)::float AS similarity_score
FROM artist a
WHERE a.artist_name % $1
AND (
    $3 < 0
    OR (
        similarity(a.artist_name, $1) < $3
        OR (similarity(a.artist_name, $1) = $3 AND a.created_at < $4)
    )
)
ORDER BY similarity(a.artist_name, $1) DESC, a.created_at DESC
LIMIT $2
`

type SearchForArtistParams struct {
	Similarity interface{}      `json:"similarity"`
	Limit      int32            `json:"limit"`
	Column3    interface{}      `json:"column_3"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type SearchForArtistRow struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	ArtistName       string           `json:"artist_name"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	SimilarityScore  float64          `json:"similarity_score"`
}

func (q *Queries) SearchForArtist(ctx context.Context, arg SearchForArtistParams) ([]SearchForArtistRow, error) {
	rows, err := q.db.Query(ctx, searchForArtist,
		arg.Similarity,
		arg.Limit,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchForArtistRow
	for rows.Next() {
		var i SearchForArtistRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SimilarityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtistPicture = `-- name: UpdateArtistPicture :exec
UPDATE artist
SET profile_image_path = $2
WHERE uuid = $1
`

type UpdateArtistPictureParams struct {
	Uuid             pgtype.UUID `json:"uuid"`
	ProfileImagePath pgtype.Text `json:"profile_image_path"`
}

func (q *Queries) UpdateArtistPicture(ctx context.Context, arg UpdateArtistPictureParams) error {
	_, err := q.db.Exec(ctx, updateArtistPicture, arg.Uuid, arg.ProfileImagePath)
	return err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :exec
UPDATE artist
SET artist_name = $2,
    bio = $3
WHERE uuid = $1
`

type UpdateArtistProfileParams struct {
	Uuid       pgtype.UUID `json:"uuid"`
	ArtistName string      `json:"artist_name"`
	Bio        pgtype.Text `json:"bio"`
}

// ---- POST
func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) error {
	_, err := q.db.Exec(ctx, updateArtistProfile, arg.Uuid, arg.ArtistName, arg.Bio)
	return err
}
