// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 02_album.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO album (from_artist, original_name, description, image_path)
VALUES ($1, $2, $3, $4)
`

type CreateAlbumParams struct {
	FromArtist   pgtype.UUID `json:"from_artist"`
	OriginalName string      `json:"original_name"`
	Description  pgtype.Text `json:"description"`
	ImagePath    pgtype.Text `json:"image_path"`
}

// ---- PUT
func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.Exec(ctx, createAlbum,
		arg.FromArtist,
		arg.OriginalName,
		arg.Description,
		arg.ImagePath,
	)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM album
WHERE uuid = $1
`

// ---- DELETE
func (q *Queries) DeleteAlbum(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlbum, uuid)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT uuid, from_artist, original_name, description, image_path, created_at, updated_at FROM album
WHERE uuid = $1
`

// ------------- Album -----------------
// ---- GET
func (q *Queries) GetAlbum(ctx context.Context, uuid pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, uuid)
	var i Album
	err := row.Scan(
		&i.Uuid,
		&i.FromArtist,
		&i.OriginalName,
		&i.Description,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumsForArtist = `-- name: GetAlbumsForArtist :many
SELECT uuid, from_artist, original_name, description, image_path, created_at, updated_at FROM album
WHERE from_artist = $1
AND (
    $3::timestamptz IS NULL
    OR (
        created_at < $3
        OR (created_at = $3 AND uuid < $4)
    )
)
ORDER BY created_at DESC, uuid DESC
LIMIT $2
`

type GetAlbumsForArtistParams struct {
	FromArtist pgtype.UUID        `json:"from_artist"`
	Limit      int32              `json:"limit"`
	Column3    pgtype.Timestamptz `json:"column_3"`
	Uuid       pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetAlbumsForArtist(ctx context.Context, arg GetAlbumsForArtistParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsForArtist,
		arg.FromArtist,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.OriginalName,
			&i.Description,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchForAlbum = `-- name: SearchForAlbum :many
SELECT
    al.uuid, al.from_artist, al.original_name, al.description, al.image_path, al.created_at, al.updated_at,
    similarity(al.original_name, $1)::float AS similarity_score
FROM album al
WHERE al.original_name % $1
AND (
    $3 < 0
    OR (
        similarity(al.original_name, $1) < $3
        OR (similarity(al.original_name, $1) = $3 AND al.created_at < $4)
    )
)
ORDER BY similarity(al.original_name, $1) DESC, al.created_at DESC
LIMIT $2
`

type SearchForAlbumParams struct {
	Similarity interface{}      `json:"similarity"`
	Limit      int32            `json:"limit"`
	Column3    interface{}      `json:"column_3"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type SearchForAlbumRow struct {
	Uuid            pgtype.UUID      `json:"uuid"`
	FromArtist      pgtype.UUID      `json:"from_artist"`
	OriginalName    string           `json:"original_name"`
	Description     pgtype.Text      `json:"description"`
	ImagePath       pgtype.Text      `json:"image_path"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	SimilarityScore float64          `json:"similarity_score"`
}

func (q *Queries) SearchForAlbum(ctx context.Context, arg SearchForAlbumParams) ([]SearchForAlbumRow, error) {
	rows, err := q.db.Query(ctx, searchForAlbum,
		arg.Similarity,
		arg.Limit,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchForAlbumRow
	for rows.Next() {
		var i SearchForAlbumRow
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.OriginalName,
			&i.Description,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SimilarityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :exec
UPDATE album
SET original_name = $2,
    description = $3
WHERE uuid = $1
`

type UpdateAlbumParams struct {
	Uuid         pgtype.UUID `json:"uuid"`
	OriginalName string      `json:"original_name"`
	Description  pgtype.Text `json:"description"`
}

// ---- POST
func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error {
	_, err := q.db.Exec(ctx, updateAlbum, arg.Uuid, arg.OriginalName, arg.Description)
	return err
}

const updateAlbumImage = `-- name: UpdateAlbumImage :exec
UPDATE album
SET image_path = $2
WHERE uuid = $1
`

type UpdateAlbumImageParams struct {
	Uuid      pgtype.UUID `json:"uuid"`
	ImagePath pgtype.Text `json:"image_path"`
}

func (q *Queries) UpdateAlbumImage(ctx context.Context, arg UpdateAlbumImageParams) error {
	_, err := q.db.Exec(ctx, updateAlbumImage, arg.Uuid, arg.ImagePath)
	return err
}
