// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 03_music.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMusic = `-- name: CreateMusic :exec
INSERT INTO music (from_artist, uploaded_by, in_album, song_name, path_in_file_storage, duration_seconds, image_path)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateMusicParams struct {
	FromArtist        pgtype.UUID `json:"from_artist"`
	UploadedBy        pgtype.UUID `json:"uploaded_by"`
	InAlbum           pgtype.UUID `json:"in_album"`
	SongName          string      `json:"song_name"`
	PathInFileStorage string      `json:"path_in_file_storage"`
	DurationSeconds   int32       `json:"duration_seconds"`
	ImagePath         pgtype.Text `json:"image_path"`
}

// ---- PUT
func (q *Queries) CreateMusic(ctx context.Context, arg CreateMusicParams) error {
	_, err := q.db.Exec(ctx, createMusic,
		arg.FromArtist,
		arg.UploadedBy,
		arg.InAlbum,
		arg.SongName,
		arg.PathInFileStorage,
		arg.DurationSeconds,
		arg.ImagePath,
	)
	return err
}

const deleteMusic = `-- name: DeleteMusic :exec
DELETE FROM music
WHERE uuid = $1
`

// ---- DELETE
func (q *Queries) DeleteMusic(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMusic, uuid)
	return err
}

const getMusic = `-- name: GetMusic :one
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE uuid = $1
`

// ------------- Music -----------------
// ---- GET
func (q *Queries) GetMusic(ctx context.Context, uuid pgtype.UUID) (Music, error) {
	row := q.db.QueryRow(ctx, getMusic, uuid)
	var i Music
	err := row.Scan(
		&i.Uuid,
		&i.FromArtist,
		&i.UploadedBy,
		&i.InAlbum,
		&i.SongName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PathInFileStorage,
		&i.ImagePath,
		&i.PlayCount,
		&i.DurationSeconds,
	)
	return i, err
}

const getMusicForAlbum = `-- name: GetMusicForAlbum :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE in_album = $1
AND (
    $3::timestamptz IS NULL
    OR (
        created_at < $3
        OR (created_at = $3 AND uuid < $4)
    )
)
ORDER BY created_at DESC, uuid DESC
LIMIT $2
`

type GetMusicForAlbumParams struct {
	InAlbum pgtype.UUID        `json:"in_album"`
	Limit   int32              `json:"limit"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Uuid    pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetMusicForAlbum(ctx context.Context, arg GetMusicForAlbumParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForAlbum,
		arg.InAlbum,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusicForArtist = `-- name: GetMusicForArtist :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE from_artist = $1
AND (
    $3::timestamptz IS NULL
    OR (
        created_at < $3
        OR (created_at = $3 AND uuid < $4)
    )
)
ORDER BY created_at DESC, uuid DESC
LIMIT $2
`

type GetMusicForArtistParams struct {
	FromArtist pgtype.UUID        `json:"from_artist"`
	Limit      int32              `json:"limit"`
	Column3    pgtype.Timestamptz `json:"column_3"`
	Uuid       pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetMusicForArtist(ctx context.Context, arg GetMusicForArtistParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForArtist,
		arg.FromArtist,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusicForUser = `-- name: GetMusicForUser :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE uploaded_by = $1
AND (
    $3::timestamptz IS NULL
    OR (
        created_at < $3
        OR (created_at = $3 AND uuid < $4)
    )
)
ORDER BY created_at DESC, uuid DESC
LIMIT $2
`

type GetMusicForUserParams struct {
	UploadedBy pgtype.UUID        `json:"uploaded_by"`
	Limit      int32              `json:"limit"`
	Column3    pgtype.Timestamptz `json:"column_3"`
	Uuid       pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetMusicForUser(ctx context.Context, arg GetMusicForUserParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForUser,
		arg.UploadedBy,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPlayCount = `-- name: IncrementPlayCount :exec
UPDATE music
SET play_count = play_count + 1
WHERE uuid = $1
`

func (q *Queries) IncrementPlayCount(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPlayCount, uuid)
	return err
}

const resetPlayCount = `-- name: ResetPlayCount :exec
UPDATE music
SET play_count = 0
WHERE uuid = $1
`

func (q *Queries) ResetPlayCount(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetPlayCount, uuid)
	return err
}

const searchForMusic = `-- name: SearchForMusic :many
SELECT
    m.uuid, m.from_artist, m.uploaded_by, m.in_album, m.song_name, m.created_at, m.updated_at, m.path_in_file_storage, m.image_path, m.play_count, m.duration_seconds,
    similarity(m.song_name, $1)::float AS similarity_score
FROM music m
WHERE m.song_name % $1
AND (
    $3 < 0
    OR (
        similarity(m.song_name, $1) < $3
        OR (similarity(m.song_name, $1) = $3 AND m.created_at < $4)
    )
)
ORDER BY similarity(m.song_name, $1) DESC, m.created_at DESC
LIMIT $2
`

type SearchForMusicParams struct {
	Similarity string           `json:"similarity"`
	Limit      int32            `json:"limit"`
	Column3    interface{}      `json:"column_3"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type SearchForMusicRow struct {
	Uuid              pgtype.UUID      `json:"uuid"`
	FromArtist        pgtype.UUID      `json:"from_artist"`
	UploadedBy        pgtype.UUID      `json:"uploaded_by"`
	InAlbum           pgtype.UUID      `json:"in_album"`
	SongName          string           `json:"song_name"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	PathInFileStorage string           `json:"path_in_file_storage"`
	ImagePath         pgtype.Text      `json:"image_path"`
	PlayCount         pgtype.Int4      `json:"play_count"`
	DurationSeconds   int32            `json:"duration_seconds"`
	SimilarityScore   float64          `json:"similarity_score"`
}

func (q *Queries) SearchForMusic(ctx context.Context, arg SearchForMusicParams) ([]SearchForMusicRow, error) {
	rows, err := q.db.Query(ctx, searchForMusic,
		arg.Similarity,
		arg.Limit,
		arg.Column3,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchForMusicRow
	for rows.Next() {
		var i SearchForMusicRow
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
			&i.SimilarityScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMusicDetails = `-- name: UpdateMusicDetails :exec
UPDATE music
SET song_name = $2,
    in_album = $3
WHERE uuid = $1
`

type UpdateMusicDetailsParams struct {
	Uuid     pgtype.UUID `json:"uuid"`
	SongName string      `json:"song_name"`
	InAlbum  pgtype.UUID `json:"in_album"`
}

// ---- POST
func (q *Queries) UpdateMusicDetails(ctx context.Context, arg UpdateMusicDetailsParams) error {
	_, err := q.db.Exec(ctx, updateMusicDetails, arg.Uuid, arg.SongName, arg.InAlbum)
	return err
}

const updateMusicImage = `-- name: UpdateMusicImage :exec
UPDATE music
SET image_path = $2
WHERE uuid = $1
`

type UpdateMusicImageParams struct {
	Uuid      pgtype.UUID `json:"uuid"`
	ImagePath pgtype.Text `json:"image_path"`
}

func (q *Queries) UpdateMusicImage(ctx context.Context, arg UpdateMusicImageParams) error {
	_, err := q.db.Exec(ctx, updateMusicImage, arg.Uuid, arg.ImagePath)
	return err
}

const updateMusicStorage = `-- name: UpdateMusicStorage :exec
UPDATE music
SET path_in_file_storage = $2,
    duration_seconds = $3
WHERE uuid = $1
`

type UpdateMusicStorageParams struct {
	Uuid              pgtype.UUID `json:"uuid"`
	PathInFileStorage string      `json:"path_in_file_storage"`
	DurationSeconds   int32       `json:"duration_seconds"`
}

func (q *Queries) UpdateMusicStorage(ctx context.Context, arg UpdateMusicStorageParams) error {
	_, err := q.db.Exec(ctx, updateMusicStorage, arg.Uuid, arg.PathInFileStorage, arg.DurationSeconds)
	return err
}
