// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 05_follows.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followArtist = `-- name: FollowArtist :exec
INSERT INTO follows (from_user, to_artist)
VALUES ($1, $2)
`

type FollowArtistParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToArtist pgtype.UUID `json:"to_artist"`
}

func (q *Queries) FollowArtist(ctx context.Context, arg FollowArtistParams) error {
	_, err := q.db.Exec(ctx, followArtist, arg.FromUser, arg.ToArtist)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (from_user, to_user)
VALUES ($1, $2)
`

type FollowUserParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToUser   pgtype.UUID `json:"to_user"`
}

// ---- PUT
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FromUser, arg.ToUser)
	return err
}

const getFollowCount = `-- name: GetFollowCount :one
SELECT COUNT(*)
FROM follows
WHERE from_user = $1
`

func (q *Queries) GetFollowCount(ctx context.Context, fromUser pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowCount, fromUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowedArtistsForUser = `-- name: GetFollowedArtistsForUser :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.country, pu.created_at, pu.updated_at
FROM follows f
         JOIN public_user pu
              ON f.to_artist = pu.uuid
WHERE f.from_user = $1
  AND (
    $3::timestamptz IS NULL
    OR (
        f.created_at < $3
        OR (f.created_at = $3 AND f.uuid < $4)
    )
    )
ORDER BY f.created_at DESC, f.uuid DESC
    LIMIT $2
`

type GetFollowedArtistsForUserParams struct {
	FromUser pgtype.UUID        `json:"from_user"`
	Limit    int32              `json:"limit"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Uuid     pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetFollowedArtistsForUser(ctx context.Context, arg GetFollowedArtistsForUserParams) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowedArtistsForUser,
		arg.FromUser,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowedUsersForUser = `-- name: GetFollowedUsersForUser :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.country, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.to_user = pu.uuid
WHERE f.from_user = $1
AND (
    $3::timestamptz IS NULL
    OR (
        f.created_at < $3
        OR (f.created_at = $3 AND f.uuid < $4)
    )
)
ORDER BY f.created_at DESC, f.uuid DESC
LIMIT $2
`

type GetFollowedUsersForUserParams struct {
	FromUser pgtype.UUID        `json:"from_user"`
	Limit    int32              `json:"limit"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Uuid     pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetFollowedUsersForUser(ctx context.Context, arg GetFollowedUsersForUserParams) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowedUsersForUser,
		arg.FromUser,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerCountForUser = `-- name: GetFollowerCountForUser :one
SELECT COUNT(*)
FROM follows
WHERE to_user = $1
`

func (q *Queries) GetFollowerCountForUser(ctx context.Context, toUser pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCountForUser, toUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowersForArtist = `-- name: GetFollowersForArtist :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.country, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.from_user = pu.uuid
WHERE f.to_artist = $1
AND (
    $3::timestamptz IS NULL
    OR (
        f.created_at < $3
        OR (f.created_at = $3 AND f.uuid < $4)
    )
)
ORDER BY f.created_at DESC, f.uuid DESC
LIMIT $2
`

type GetFollowersForArtistParams struct {
	ToArtist pgtype.UUID        `json:"to_artist"`
	Limit    int32              `json:"limit"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Uuid     pgtype.UUID        `json:"uuid"`
}

func (q *Queries) GetFollowersForArtist(ctx context.Context, arg GetFollowersForArtistParams) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowersForArtist,
		arg.ToArtist,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersForUser = `-- name: GetFollowersForUser :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.country, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.from_user = pu.uuid
WHERE f.to_user = $1
AND (
    $3::timestamptz IS NULL
    OR (
        f.created_at < $3
        OR (f.created_at = $3 AND f.uuid < $4)
    )
)
ORDER BY f.created_at DESC, f.uuid DESC
LIMIT $2
`

type GetFollowersForUserParams struct {
	ToUser  pgtype.UUID        `json:"to_user"`
	Limit   int32              `json:"limit"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Uuid    pgtype.UUID        `json:"uuid"`
}

// ------------- Follows -----------------
// ---- GET
func (q *Queries) GetFollowersForUser(ctx context.Context, arg GetFollowersForUserParams) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowersForUser,
		arg.ToUser,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCountForArtist = `-- name: GetFollowingCountForArtist :one
SELECT COUNT(*)
FROM follows
WHERE to_artist = $1
`

func (q *Queries) GetFollowingCountForArtist(ctx context.Context, toArtist pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowingCountForArtist, toArtist)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isFollowingArtist = `-- name: IsFollowingArtist :one
SELECT EXISTS (
    SELECT 1
    FROM follows f
    WHERE f.from_user = $1
    AND f.to_artist = $2
)
`

type IsFollowingArtistParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToArtist pgtype.UUID `json:"to_artist"`
}

func (q *Queries) IsFollowingArtist(ctx context.Context, arg IsFollowingArtistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingArtist, arg.FromUser, arg.ToArtist)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFollowingUser = `-- name: IsFollowingUser :one
SELECT EXISTS (
    SELECT 1
    FROM follows f
    WHERE f.from_user = $1
    AND f.to_user = $2
)
`

type IsFollowingUserParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToUser   pgtype.UUID `json:"to_user"`
}

func (q *Queries) IsFollowingUser(ctx context.Context, arg IsFollowingUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingUser, arg.FromUser, arg.ToUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowArtist = `-- name: UnfollowArtist :exec
DELETE FROM follows
WHERE from_user = $1 AND to_artist = $2
`

type UnfollowArtistParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToArtist pgtype.UUID `json:"to_artist"`
}

func (q *Queries) UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) error {
	_, err := q.db.Exec(ctx, unfollowArtist, arg.FromUser, arg.ToArtist)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE from_user = $1 AND to_user = $2
`

type UnfollowUserParams struct {
	FromUser pgtype.UUID `json:"from_user"`
	ToUser   pgtype.UUID `json:"to_user"`
}

// ---- DELETE
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FromUser, arg.ToUser)
	return err
}
