// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 08_listening_history.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListeningHistoryEntry = `-- name: AddListeningHistoryEntry :exec
INSERT INTO listening_history (user_uuid, music_uuid, listen_duration_seconds, completion_percentage)
VALUES ($1, $2, $3, $4)
`

type AddListeningHistoryEntryParams struct {
	UserUuid              pgtype.UUID    `json:"user_uuid"`
	MusicUuid             pgtype.UUID    `json:"music_uuid"`
	ListenDurationSeconds pgtype.Int4    `json:"listen_duration_seconds"`
	CompletionPercentage  pgtype.Numeric `json:"completion_percentage"`
}

// ---- PUT
func (q *Queries) AddListeningHistoryEntry(ctx context.Context, arg AddListeningHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, addListeningHistoryEntry,
		arg.UserUuid,
		arg.MusicUuid,
		arg.ListenDurationSeconds,
		arg.CompletionPercentage,
	)
	return err
}

const getListeningHistoryForUser = `-- name: GetListeningHistoryForUser :many
SELECT uuid, user_uuid, music_uuid, played_at, listen_duration_seconds, completion_percentage
FROM listening_history
WHERE user_uuid = $1
AND (
    $3::timestamptz IS NULL
    OR (
         played_at < $3
         OR (played_at = $3 AND uuid < $4)
       )
)
ORDER BY played_at DESC, uuid DESC
LIMIT $2
`

type GetListeningHistoryForUserParams struct {
	UserUuid pgtype.UUID        `json:"user_uuid"`
	Limit    int32              `json:"limit"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Uuid     pgtype.UUID        `json:"uuid"`
}

// ------------- ListeningHistory -----------------
// ---- GET
func (q *Queries) GetListeningHistoryForUser(ctx context.Context, arg GetListeningHistoryForUserParams) ([]ListeningHistory, error) {
	rows, err := q.db.Query(ctx, getListeningHistoryForUser,
		arg.UserUuid,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListeningHistory
	for rows.Next() {
		var i ListeningHistory
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.MusicUuid,
			&i.PlayedAt,
			&i.ListenDurationSeconds,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMusicForUser = `-- name: GetTopMusicForUser :many
SELECT music_uuid, COUNT(*) as play_count
FROM listening_history
WHERE user_uuid = $1
GROUP BY music_uuid
HAVING (
    $3::uuid IS NULL
    OR (
        COUNT(*) < $4
        OR (COUNT(*) = $4 AND music_uuid < $3)
    )
)
ORDER BY play_count DESC, music_uuid DESC
LIMIT $2
`

type GetTopMusicForUserParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Limit    int32       `json:"limit"`
	Column3  pgtype.UUID `json:"column_3"`
	Column4  interface{} `json:"column_4"`
}

type GetTopMusicForUserRow struct {
	MusicUuid pgtype.UUID `json:"music_uuid"`
	PlayCount int64       `json:"play_count"`
}

func (q *Queries) GetTopMusicForUser(ctx context.Context, arg GetTopMusicForUserParams) ([]GetTopMusicForUserRow, error) {
	rows, err := q.db.Query(ctx, getTopMusicForUser,
		arg.UserUuid,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMusicForUserRow
	for rows.Next() {
		var i GetTopMusicForUserRow
		if err := rows.Scan(&i.MusicUuid, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
