// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 08_listening_history.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListeningHistoryEntry = `-- name: AddListeningHistoryEntry :exec
INSERT INTO listening_history (user_uuid, music_uuid, listen_duration_seconds, completion_percentage)
VALUES ($1, $2, $3, $4)
`

type AddListeningHistoryEntryParams struct {
	UserUuid              pgtype.UUID    `json:"user_uuid"`
	MusicUuid             pgtype.UUID    `json:"music_uuid"`
	ListenDurationSeconds pgtype.Int4    `json:"listen_duration_seconds"`
	CompletionPercentage  pgtype.Numeric `json:"completion_percentage"`
}

// ---- PUT
func (q *Queries) AddListeningHistoryEntry(ctx context.Context, arg AddListeningHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, addListeningHistoryEntry,
		arg.UserUuid,
		arg.MusicUuid,
		arg.ListenDurationSeconds,
		arg.CompletionPercentage,
	)
	return err
}

const getListeningHistoryForUser = `-- name: GetListeningHistoryForUser :many
SELECT
    lh.uuid,
    lh.user_uuid,
    lh.music_uuid,
    m.song_name,
    a.artist_name,
    m.from_artist as artist_uuid,
    lh.played_at as listened_at,
    lh.listen_duration_seconds,
    lh.completion_percentage
FROM listening_history lh
INNER JOIN music m ON lh.music_uuid = m.uuid
INNER JOIN artist a ON m.from_artist = a.uuid
WHERE lh.user_uuid = $1
AND (
    $3::timestamptz IS NULL
    OR (
         lh.played_at < $3
         OR (lh.played_at = $3 AND lh.uuid < $4)
       )
)
ORDER BY lh.played_at DESC, lh.uuid DESC
LIMIT $2
`

type GetListeningHistoryForUserParams struct {
	UserUuid pgtype.UUID        `json:"user_uuid"`
	Limit    int32              `json:"limit"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	Uuid     pgtype.UUID        `json:"uuid"`
}

type GetListeningHistoryForUserRow struct {
	Uuid                  pgtype.UUID      `json:"uuid"`
	UserUuid              pgtype.UUID      `json:"user_uuid"`
	MusicUuid             pgtype.UUID      `json:"music_uuid"`
	SongName              string           `json:"song_name"`
	ArtistName            string           `json:"artist_name"`
	ArtistUuid            pgtype.UUID      `json:"artist_uuid"`
	ListenedAt            pgtype.Timestamp `json:"listened_at"`
	ListenDurationSeconds pgtype.Int4      `json:"listen_duration_seconds"`
	CompletionPercentage  pgtype.Numeric   `json:"completion_percentage"`
}

// ------------- ListeningHistory -----------------
// ---- GET
func (q *Queries) GetListeningHistoryForUser(ctx context.Context, arg GetListeningHistoryForUserParams) ([]GetListeningHistoryForUserRow, error) {
	rows, err := q.db.Query(ctx, getListeningHistoryForUser,
		arg.UserUuid,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListeningHistoryForUserRow
	for rows.Next() {
		var i GetListeningHistoryForUserRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.MusicUuid,
			&i.SongName,
			&i.ArtistName,
			&i.ArtistUuid,
			&i.ListenedAt,
			&i.ListenDurationSeconds,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMusicForUser = `-- name: GetTopMusicForUser :many
SELECT
    lh.music_uuid,
    m.song_name,
    a.artist_name,
    m.from_artist as artist_uuid,
    COUNT(*) as play_count
FROM listening_history lh
INNER JOIN music m ON lh.music_uuid = m.uuid
INNER JOIN artist a ON m.from_artist = a.uuid
WHERE lh.user_uuid = $1
GROUP BY lh.music_uuid, m.song_name, a.artist_name, m.from_artist
HAVING (
    $3::uuid IS NULL
    OR (
        COUNT(*) < $4
        OR (COUNT(*) = $4 AND lh.music_uuid < $3)
    )
)
ORDER BY play_count DESC, lh.music_uuid DESC
LIMIT $2
`

type GetTopMusicForUserParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	Limit    int32       `json:"limit"`
	Column3  pgtype.UUID `json:"column_3"`
	Column4  interface{} `json:"column_4"`
}

type GetTopMusicForUserRow struct {
	MusicUuid  pgtype.UUID `json:"music_uuid"`
	SongName   string      `json:"song_name"`
	ArtistName string      `json:"artist_name"`
	ArtistUuid pgtype.UUID `json:"artist_uuid"`
	PlayCount  int64       `json:"play_count"`
}

func (q *Queries) GetTopMusicForUser(ctx context.Context, arg GetTopMusicForUserParams) ([]GetTopMusicForUserRow, error) {
	rows, err := q.db.Query(ctx, getTopMusicForUser,
		arg.UserUuid,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMusicForUserRow
	for rows.Next() {
		var i GetTopMusicForUserRow
		if err := rows.Scan(
			&i.MusicUuid,
			&i.SongName,
			&i.ArtistName,
			&i.ArtistUuid,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
