// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 09_refresh_tokens.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getDevicesForUser = `-- name: GetDevicesForUser :many
SELECT uuid, device_id, device_name, created_at, last_used_at, expires_at
FROM refresh_tokens
WHERE user_uuid = $1 AND expires_at > CURRENT_TIMESTAMP
ORDER BY last_used_at DESC
`

type GetDevicesForUserRow struct {
	Uuid       pgtype.UUID      `json:"uuid"`
	DeviceID   pgtype.UUID      `json:"device_id"`
	DeviceName pgtype.Text      `json:"device_name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) GetDevicesForUser(ctx context.Context, userUuid pgtype.UUID) ([]GetDevicesForUserRow, error) {
	rows, err := q.db.Query(ctx, getDevicesForUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDevicesForUserRow
	for rows.Next() {
		var i GetDevicesForUserRow
		if err := rows.Scan(
			&i.Uuid,
			&i.DeviceID,
			&i.DeviceName,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT uuid, user_uuid, device_id, token_hash, device_name, expires_at, created_at, last_used_at FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.DeviceID,
		&i.TokenHash,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeAllDevicesForUser = `-- name: RevokeAllDevicesForUser :exec
DELETE FROM refresh_tokens
WHERE user_uuid = $1
`

func (q *Queries) RevokeAllDevicesForUser(ctx context.Context, userUuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllDevicesForUser, userUuid)
	return err
}

const revokeDevice = `-- name: RevokeDevice :exec
DELETE FROM refresh_tokens
WHERE user_uuid = $1 AND device_id = $2
`

type RevokeDeviceParams struct {
	UserUuid pgtype.UUID `json:"user_uuid"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.UserUuid, arg.DeviceID)
	return err
}

const upsertRefreshToken = `-- name: UpsertRefreshToken :one
INSERT INTO refresh_tokens (user_uuid, device_id, token_hash, device_name, expires_at, created_at, last_used_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (user_uuid, device_id)
DO UPDATE SET
    token_hash = EXCLUDED.token_hash,
    device_name = EXCLUDED.device_name,
    expires_at = EXCLUDED.expires_at,
    last_used_at = CURRENT_TIMESTAMP
RETURNING uuid, user_uuid, device_id, token_hash, device_name, expires_at, created_at, last_used_at
`

type UpsertRefreshTokenParams struct {
	UserUuid   pgtype.UUID      `json:"user_uuid"`
	DeviceID   pgtype.UUID      `json:"device_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceName pgtype.Text      `json:"device_name"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) UpsertRefreshToken(ctx context.Context, arg UpsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, upsertRefreshToken,
		arg.UserUuid,
		arg.DeviceID,
		arg.TokenHash,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.DeviceID,
		&i.TokenHash,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const validateAndUpdateRefreshToken = `-- name: ValidateAndUpdateRefreshToken :one
UPDATE refresh_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP
RETURNING uuid, user_uuid, device_id, token_hash, device_name, expires_at, created_at, last_used_at
`

func (q *Queries) ValidateAndUpdateRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, validateAndUpdateRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.Uuid,
		&i.UserUuid,
		&i.DeviceID,
		&i.TokenHash,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
