// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql_handler

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArtistMemberRole string

const (
	ArtistMemberRoleOwner   ArtistMemberRole = "owner"
	ArtistMemberRoleManager ArtistMemberRole = "manager"
	ArtistMemberRoleMember  ArtistMemberRole = "member"
)

func (e *ArtistMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtistMemberRole(s)
	case string:
		*e = ArtistMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtistMemberRole: %T", src)
	}
	return nil
}

type NullArtistMemberRole struct {
	ArtistMemberRole ArtistMemberRole
	Valid            bool // Valid is true if ArtistMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtistMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ArtistMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtistMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtistMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtistMemberRole), nil
}

type Album struct {
	Uuid         pgtype.UUID
	FromArtist   pgtype.UUID
	OriginalName string
	Description  pgtype.Text
	ImagePath    pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Artist struct {
	Uuid             pgtype.UUID
	ArtistName       string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type ArtistMember struct {
	Uuid       pgtype.UUID
	ArtistUuid pgtype.UUID
	UserUuid   pgtype.UUID
	Role       ArtistMemberRole
	JoinedAt   pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Follow struct {
	Uuid      pgtype.UUID
	FromUser  pgtype.UUID
	ToUser    pgtype.UUID
	ToArtist  pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type Like struct {
	Uuid      pgtype.UUID
	FromUser  pgtype.UUID
	ToMusic   pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type ListeningHistory struct {
	Uuid                  pgtype.UUID
	UserUuid              pgtype.UUID
	MusicUuid             pgtype.UUID
	PlayedAt              pgtype.Timestamp
	ListenDurationSeconds pgtype.Int4
	CompletionPercentage  pgtype.Numeric
}

type Music struct {
	Uuid              pgtype.UUID
	FromArtist        pgtype.UUID
	UploadedBy        pgtype.UUID
	InAlbum           pgtype.UUID
	SongName          string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	PathInFileStorage string
	ImagePath         pgtype.Text
	PlayCount         pgtype.Int4
	DurationSeconds   int32
}

type MusicTag struct {
	TagName        string
	TagDescription pgtype.Text
	CreatedAt      pgtype.Timestamp
}

type Playlist struct {
	Uuid         pgtype.UUID
	FromUser     pgtype.UUID
	OriginalName string
	Description  pgtype.Text
	IsPublic     pgtype.Bool
	ImagePath    pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type PlaylistTrack struct {
	Uuid         pgtype.UUID
	MusicUuid    pgtype.UUID
	Position     int32
	PlaylistUuid pgtype.UUID
	AddedAt      pgtype.Timestamp
}

type PublicUser struct {
	Uuid             pgtype.UUID
	Username         string
	Email            string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type TagAssignment struct {
	Uuid      pgtype.UUID
	MusicUuid pgtype.UUID
	TagName   string
	CreatedAt pgtype.Timestamp
}

type User struct {
	Uuid             pgtype.UUID
	Username         string
	Email            string
	HashedPassword   string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}
