// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql_handler

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArtistMemberRole string

const (
	ArtistMemberRoleOwner   ArtistMemberRole = "owner"
	ArtistMemberRoleManager ArtistMemberRole = "manager"
	ArtistMemberRoleMember  ArtistMemberRole = "member"
)

func (e *ArtistMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtistMemberRole(s)
	case string:
		*e = ArtistMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtistMemberRole: %T", src)
	}
	return nil
}

type NullArtistMemberRole struct {
	ArtistMemberRole ArtistMemberRole `json:"artist_member_role"`
	Valid            bool             `json:"valid"` // Valid is true if ArtistMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtistMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ArtistMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtistMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtistMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtistMemberRole), nil
}

type Album struct {
	Uuid         pgtype.UUID      `json:"uuid"`
	FromArtist   pgtype.UUID      `json:"from_artist"`
	OriginalName string           `json:"original_name"`
	Description  pgtype.Text      `json:"description"`
	ImagePath    pgtype.Text      `json:"image_path"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Artist struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	ArtistName       string           `json:"artist_name"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type ArtistMember struct {
	Uuid       pgtype.UUID      `json:"uuid"`
	ArtistUuid pgtype.UUID      `json:"artist_uuid"`
	UserUuid   pgtype.UUID      `json:"user_uuid"`
	Role       ArtistMemberRole `json:"role"`
	JoinedAt   pgtype.Timestamp `json:"joined_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Follow struct {
	Uuid      pgtype.UUID      `json:"uuid"`
	FromUser  pgtype.UUID      `json:"from_user"`
	ToUser    pgtype.UUID      `json:"to_user"`
	ToArtist  pgtype.UUID      `json:"to_artist"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Like struct {
	Uuid      pgtype.UUID      `json:"uuid"`
	FromUser  pgtype.UUID      `json:"from_user"`
	ToMusic   pgtype.UUID      `json:"to_music"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type ListeningHistory struct {
	Uuid                  pgtype.UUID      `json:"uuid"`
	UserUuid              pgtype.UUID      `json:"user_uuid"`
	MusicUuid             pgtype.UUID      `json:"music_uuid"`
	PlayedAt              pgtype.Timestamp `json:"played_at"`
	ListenDurationSeconds pgtype.Int4      `json:"listen_duration_seconds"`
	CompletionPercentage  pgtype.Numeric   `json:"completion_percentage"`
}

type Music struct {
	Uuid              pgtype.UUID      `json:"uuid"`
	FromArtist        pgtype.UUID      `json:"from_artist"`
	UploadedBy        pgtype.UUID      `json:"uploaded_by"`
	InAlbum           pgtype.UUID      `json:"in_album"`
	SongName          string           `json:"song_name"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	PathInFileStorage string           `json:"path_in_file_storage"`
	ImagePath         pgtype.Text      `json:"image_path"`
	PlayCount         pgtype.Int4      `json:"play_count"`
	DurationSeconds   int32            `json:"duration_seconds"`
}

type MusicTag struct {
	TagName        string           `json:"tag_name"`
	TagDescription pgtype.Text      `json:"tag_description"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Playlist struct {
	Uuid         pgtype.UUID      `json:"uuid"`
	FromUser     pgtype.UUID      `json:"from_user"`
	OriginalName string           `json:"original_name"`
	Description  pgtype.Text      `json:"description"`
	IsPublic     pgtype.Bool      `json:"is_public"`
	ImagePath    pgtype.Text      `json:"image_path"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type PlaylistTrack struct {
	Uuid         pgtype.UUID      `json:"uuid"`
	MusicUuid    pgtype.UUID      `json:"music_uuid"`
	Position     int32            `json:"position"`
	PlaylistUuid pgtype.UUID      `json:"playlist_uuid"`
	AddedAt      pgtype.Timestamp `json:"added_at"`
}

type PublicUser struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	Country          string           `json:"country"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	Uuid       pgtype.UUID      `json:"uuid"`
	UserUuid   pgtype.UUID      `json:"user_uuid"`
	DeviceID   pgtype.UUID      `json:"device_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceName pgtype.Text      `json:"device_name"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

type TagAssignment struct {
	Uuid      pgtype.UUID      `json:"uuid"`
	MusicUuid pgtype.UUID      `json:"music_uuid"`
	TagName   string           `json:"tag_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	Uuid             pgtype.UUID      `json:"uuid"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	HashedPassword   string           `json:"hashed_password"`
	Bio              pgtype.Text      `json:"bio"`
	ProfileImagePath pgtype.Text      `json:"profile_image_path"`
	Country          string           `json:"country"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}
