// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 01_artist.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToArtist = `-- name: AddUserToArtist :exec
INSERT INTO artist_member (artist_uuid, user_uuid, role)
VALUES ($1, $2, $3)
`

type AddUserToArtistParams struct {
	ArtistUuid pgtype.UUID
	UserUuid   pgtype.UUID
	Role       ArtistMemberRole
}

// ---- PUT
func (q *Queries) AddUserToArtist(ctx context.Context, arg AddUserToArtistParams) error {
	_, err := q.db.Exec(ctx, addUserToArtist, arg.ArtistUuid, arg.UserUuid, arg.Role)
	return err
}

const changeUserRole = `-- name: ChangeUserRole :exec
UPDATE artist_member
SET role = $3
WHERE artist_uuid = $1 AND user_uuid = $2
`

type ChangeUserRoleParams struct {
	ArtistUuid pgtype.UUID
	UserUuid   pgtype.UUID
	Role       ArtistMemberRole
}

// ---- POST
func (q *Queries) ChangeUserRole(ctx context.Context, arg ChangeUserRoleParams) error {
	_, err := q.db.Exec(ctx, changeUserRole, arg.ArtistUuid, arg.UserUuid, arg.Role)
	return err
}

const createArtist = `-- name: CreateArtist :exec
WITH new_artist as (
    INSERT INTO artist (artist_name, bio, profile_image_path)
    VALUES ($2, $3, $4)
    RETURNING uuid
)
INSERT INTO artist_member (artist_uuid, user_uuid, "role")
SELECT uuid, $1, 'owner'
FROM new_artist
`

type CreateArtistParams struct {
	UserUuid         pgtype.UUID
	ArtistName       string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
}

// ---- PUT
func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) error {
	_, err := q.db.Exec(ctx, createArtist,
		arg.UserUuid,
		arg.ArtistName,
		arg.Bio,
		arg.ProfileImagePath,
	)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT uuid, artist_name, bio, profile_image_path, created_at, updated_at FROM artist
WHERE uuid = $1
`

// ------------- Artists -----------------
// ---- GET
func (q *Queries) GetArtist(ctx context.Context, uuid pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, uuid)
	var i Artist
	err := row.Scan(
		&i.Uuid,
		&i.ArtistName,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtistForUser = `-- name: GetArtistForUser :many
SELECT art.uuid, art.artist_name, art.bio, art.profile_image_path, art.created_at, art.updated_at, am.role, am.joined_at
FROM artist_member am
         JOIN artist art
              ON am.artist_uuid = art.uuid
WHERE am.user_uuid = $1
`

type GetArtistForUserRow struct {
	Uuid             pgtype.UUID
	ArtistName       string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	Role             ArtistMemberRole
	JoinedAt         pgtype.Timestamp
}

func (q *Queries) GetArtistForUser(ctx context.Context, userUuid pgtype.UUID) ([]GetArtistForUserRow, error) {
	rows, err := q.db.Query(ctx, getArtistForUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistForUserRow
	for rows.Next() {
		var i GetArtistForUserRow
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistsAlphabetically = `-- name: GetArtistsAlphabetically :many
SELECT uuid, artist_name, bio, profile_image_path, created_at, updated_at FROM artist
ORDER BY artist_name
`

func (q *Queries) GetArtistsAlphabetically(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistsAlphabetically)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersRepresentingArtist = `-- name: GetUsersRepresentingArtist :many

SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at, am.role, am.joined_at
FROM artist_member am
         JOIN public_user pu
              ON am.user_uuid = pu.uuid
WHERE am.artist_uuid = $1
`

type GetUsersRepresentingArtistRow struct {
	Uuid             pgtype.UUID
	Username         string
	Email            string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	Role             ArtistMemberRole
	JoinedAt         pgtype.Timestamp
}

// ---- DELETE
// deletes are overrated
// ------------- ArtistMember -----------------
// ---- GET
func (q *Queries) GetUsersRepresentingArtist(ctx context.Context, artistUuid pgtype.UUID) ([]GetUsersRepresentingArtistRow, error) {
	rows, err := q.db.Query(ctx, getUsersRepresentingArtist, artistUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRepresentingArtistRow
	for rows.Next() {
		var i GetUsersRepresentingArtistRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromArtist = `-- name: RemoveUserFromArtist :exec
DELETE FROM artist_member
WHERE artist_uuid = $1 AND user_uuid = $2
`

type RemoveUserFromArtistParams struct {
	ArtistUuid pgtype.UUID
	UserUuid   pgtype.UUID
}

// ---- DELETE
func (q *Queries) RemoveUserFromArtist(ctx context.Context, arg RemoveUserFromArtistParams) error {
	_, err := q.db.Exec(ctx, removeUserFromArtist, arg.ArtistUuid, arg.UserUuid)
	return err
}

const updateArtistPicture = `-- name: UpdateArtistPicture :exec
UPDATE artist
SET profile_image_path = $2
WHERE uuid = $1
`

type UpdateArtistPictureParams struct {
	Uuid             pgtype.UUID
	ProfileImagePath pgtype.Text
}

func (q *Queries) UpdateArtistPicture(ctx context.Context, arg UpdateArtistPictureParams) error {
	_, err := q.db.Exec(ctx, updateArtistPicture, arg.Uuid, arg.ProfileImagePath)
	return err
}

const updateArtistProfile = `-- name: UpdateArtistProfile :exec
UPDATE artist
SET artist_name = $2,
    bio = $3
WHERE uuid = $1
`

type UpdateArtistProfileParams struct {
	Uuid       pgtype.UUID
	ArtistName string
	Bio        pgtype.Text
}

// ---- POST
func (q *Queries) UpdateArtistProfile(ctx context.Context, arg UpdateArtistProfileParams) error {
	_, err := q.db.Exec(ctx, updateArtistProfile, arg.Uuid, arg.ArtistName, arg.Bio)
	return err
}
