// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 03_music.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMusic = `-- name: CreateMusic :exec
INSERT INTO music (from_artist, uploaded_by, in_album, song_name, path_in_file_storage, duration_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMusicParams struct {
	FromArtist        pgtype.UUID
	UploadedBy        pgtype.UUID
	InAlbum           pgtype.UUID
	SongName          string
	PathInFileStorage string
	DurationSeconds   int32
}

// ---- PUT
func (q *Queries) CreateMusic(ctx context.Context, arg CreateMusicParams) error {
	_, err := q.db.Exec(ctx, createMusic,
		arg.FromArtist,
		arg.UploadedBy,
		arg.InAlbum,
		arg.SongName,
		arg.PathInFileStorage,
		arg.DurationSeconds,
	)
	return err
}

const deleteMusic = `-- name: DeleteMusic :exec
DELETE FROM music
WHERE uuid = $1
`

// ---- DELETE
func (q *Queries) DeleteMusic(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMusic, uuid)
	return err
}

const getMusic = `-- name: GetMusic :one
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE uuid = $1
`

// ------------- Music -----------------
// ---- GET
func (q *Queries) GetMusic(ctx context.Context, uuid pgtype.UUID) (Music, error) {
	row := q.db.QueryRow(ctx, getMusic, uuid)
	var i Music
	err := row.Scan(
		&i.Uuid,
		&i.FromArtist,
		&i.UploadedBy,
		&i.InAlbum,
		&i.SongName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PathInFileStorage,
		&i.ImagePath,
		&i.PlayCount,
		&i.DurationSeconds,
	)
	return i, err
}

const getMusicForAlbum = `-- name: GetMusicForAlbum :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE in_album = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMusicForAlbumParams struct {
	InAlbum pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) GetMusicForAlbum(ctx context.Context, arg GetMusicForAlbumParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForAlbum, arg.InAlbum, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusicForArtist = `-- name: GetMusicForArtist :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE from_artist = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMusicForArtistParams struct {
	FromArtist pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) GetMusicForArtist(ctx context.Context, arg GetMusicForArtistParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForArtist, arg.FromArtist, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusicForUser = `-- name: GetMusicForUser :many
SELECT uuid, from_artist, uploaded_by, in_album, song_name, created_at, updated_at, path_in_file_storage, image_path, play_count, duration_seconds FROM music
WHERE uploaded_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMusicForUserParams struct {
	UploadedBy pgtype.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) GetMusicForUser(ctx context.Context, arg GetMusicForUserParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForUser, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPlayCount = `-- name: IncrementPlayCount :exec
UPDATE music
SET play_count = play_count + 1
WHERE uuid = $1
`

func (q *Queries) IncrementPlayCount(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPlayCount, uuid)
	return err
}

const resetPlayCount = `-- name: ResetPlayCount :exec
UPDATE music
SET play_count = 0
WHERE uuid = $1
`

func (q *Queries) ResetPlayCount(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetPlayCount, uuid)
	return err
}

const updateMusicDetails = `-- name: UpdateMusicDetails :exec

UPDATE music
SET song_name = $2,
    in_album = $3
WHERE uuid = $1
`

type UpdateMusicDetailsParams struct {
	Uuid     pgtype.UUID
	SongName string
	InAlbum  pgtype.UUID
}

// TODO: name: SearchForMusic :many
// ---- POST
func (q *Queries) UpdateMusicDetails(ctx context.Context, arg UpdateMusicDetailsParams) error {
	_, err := q.db.Exec(ctx, updateMusicDetails, arg.Uuid, arg.SongName, arg.InAlbum)
	return err
}

const updateMusicStorage = `-- name: UpdateMusicStorage :exec
UPDATE music
SET path_in_file_storage = $2,
    duration_seconds = $3
WHERE uuid = $1
`

type UpdateMusicStorageParams struct {
	Uuid              pgtype.UUID
	PathInFileStorage string
	DurationSeconds   int32
}

func (q *Queries) UpdateMusicStorage(ctx context.Context, arg UpdateMusicStorageParams) error {
	_, err := q.db.Exec(ctx, updateMusicStorage, arg.Uuid, arg.PathInFileStorage, arg.DurationSeconds)
	return err
}
