// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 04_likes.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLikeCount = `-- name: GetLikeCount :one
SELECT COUNT(*) FROM likes
WHERE to_music = $1
`

func (q *Queries) GetLikeCount(ctx context.Context, toMusic pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLikeCount, toMusic)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLikesForMusic = `-- name: GetLikesForMusic :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at
FROM likes l
JOIN public_user pu
    ON l.from_user = pu.uuid
WHERE l.to_music = $1
`

// ------------- Likes -----------------
// ---- GET
func (q *Queries) GetLikesForMusic(ctx context.Context, toMusic pgtype.UUID) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getLikesForMusic, toMusic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesForUser = `-- name: GetLikesForUser :many
SELECT m.uuid, m.from_artist, m.uploaded_by, m.in_album, m.song_name, m.created_at, m.updated_at, m.path_in_file_storage, m.image_path, m.play_count, m.duration_seconds
FROM likes l
JOIN music m
    ON l.to_music = m.uuid
WHERE l.from_user = $1
`

func (q *Queries) GetLikesForUser(ctx context.Context, fromUser pgtype.UUID) ([]Music, error) {
	rows, err := q.db.Query(ctx, getLikesForUser, fromUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLiked = `-- name: IsLiked :one
SELECT EXISTS (
    SELECT 1
    FROM likes l
    WHERE l.from_user = $1
    AND l.to_music = $2
)
`

type IsLikedParams struct {
	FromUser pgtype.UUID
	ToMusic  pgtype.UUID
}

func (q *Queries) IsLiked(ctx context.Context, arg IsLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isLiked, arg.FromUser, arg.ToMusic)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeMusic = `-- name: LikeMusic :exec
INSERT INTO likes (from_user, to_music)
VALUES ($1, $2)
`

type LikeMusicParams struct {
	FromUser pgtype.UUID
	ToMusic  pgtype.UUID
}

// ---- PUT
func (q *Queries) LikeMusic(ctx context.Context, arg LikeMusicParams) error {
	_, err := q.db.Exec(ctx, likeMusic, arg.FromUser, arg.ToMusic)
	return err
}

const unlikeMusic = `-- name: UnlikeMusic :exec
DELETE FROM likes
WHERE from_user = $1 AND to_music = $2
`

type UnlikeMusicParams struct {
	FromUser pgtype.UUID
	ToMusic  pgtype.UUID
}

// ---- DELETE
func (q *Queries) UnlikeMusic(ctx context.Context, arg UnlikeMusicParams) error {
	_, err := q.db.Exec(ctx, unlikeMusic, arg.FromUser, arg.ToMusic)
	return err
}
