// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 05_follows.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followArtist = `-- name: FollowArtist :exec
INSERT INTO follows (from_user, to_artist)
VALUES ($1, $2)
`

type FollowArtistParams struct {
	FromUser pgtype.UUID
	ToArtist pgtype.UUID
}

func (q *Queries) FollowArtist(ctx context.Context, arg FollowArtistParams) error {
	_, err := q.db.Exec(ctx, followArtist, arg.FromUser, arg.ToArtist)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (from_user, to_user)
VALUES ($1, $2)
`

type FollowUserParams struct {
	FromUser pgtype.UUID
	ToUser   pgtype.UUID
}

// ---- PUT
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FromUser, arg.ToUser)
	return err
}

const getFollowersForArtist = `-- name: GetFollowersForArtist :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.from_user = pu.uuid
WHERE f.to_artist = $1
`

func (q *Queries) GetFollowersForArtist(ctx context.Context, toArtist pgtype.UUID) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowersForArtist, toArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowersForUser = `-- name: GetFollowersForUser :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.from_user = pu.uuid
WHERE f.to_user = $1
`

// ------------- Follows -----------------
// ---- GET
func (q *Queries) GetFollowersForUser(ctx context.Context, toUser pgtype.UUID) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowersForUser, toUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingArtistsForUser = `-- name: GetFollowingArtistsForUser :many
SELECT art.uuid, art.artist_name, art.bio, art.profile_image_path, art.created_at, art.updated_at
FROM follows f
    JOIN artist art
        ON f.to_artist = art.uuid
WHERE f.from_user = $1
    AND f.to_artist IS NOT NULL
`

func (q *Queries) GetFollowingArtistsForUser(ctx context.Context, fromUser pgtype.UUID) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getFollowingArtistsForUser, fromUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.Uuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingUsersForUser = `-- name: GetFollowingUsersForUser :many
SELECT pu.uuid, pu.username, pu.email, pu.bio, pu.profile_image_path, pu.created_at, pu.updated_at
FROM follows f
JOIN public_user pu
    ON f.to_user = pu.uuid
WHERE f.from_user = $1
    AND f.to_user IS NOT NULL
`

func (q *Queries) GetFollowingUsersForUser(ctx context.Context, fromUser pgtype.UUID) ([]PublicUser, error) {
	rows, err := q.db.Query(ctx, getFollowingUsersForUser, fromUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicUser
	for rows.Next() {
		var i PublicUser
		if err := rows.Scan(
			&i.Uuid,
			&i.Username,
			&i.Email,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowingArtist = `-- name: IsFollowingArtist :one
SELECT EXISTS (
    SELECT 1
    FROM follows f
    WHERE f.from_user = $1
    AND f.to_artist = $2
)
`

type IsFollowingArtistParams struct {
	FromUser pgtype.UUID
	ToArtist pgtype.UUID
}

func (q *Queries) IsFollowingArtist(ctx context.Context, arg IsFollowingArtistParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingArtist, arg.FromUser, arg.ToArtist)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFollowingUser = `-- name: IsFollowingUser :one
SELECT EXISTS (
    SELECT 1
    FROM follows f
    WHERE f.from_user = $1
    AND f.to_user = $2
)
`

type IsFollowingUserParams struct {
	FromUser pgtype.UUID
	ToUser   pgtype.UUID
}

func (q *Queries) IsFollowingUser(ctx context.Context, arg IsFollowingUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingUser, arg.FromUser, arg.ToUser)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowArtist = `-- name: UnfollowArtist :exec
DELETE FROM follows
WHERE from_user = $1 AND to_artist = $2
`

type UnfollowArtistParams struct {
	FromUser pgtype.UUID
	ToArtist pgtype.UUID
}

func (q *Queries) UnfollowArtist(ctx context.Context, arg UnfollowArtistParams) error {
	_, err := q.db.Exec(ctx, unfollowArtist, arg.FromUser, arg.ToArtist)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE from_user = $1 AND to_user = $2
`

type UnfollowUserParams struct {
	FromUser pgtype.UUID
	ToUser   pgtype.UUID
}

// ---- DELETE
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FromUser, arg.ToUser)
	return err
}
