// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 06_tags.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTagToMusic = `-- name: AssignTagToMusic :exec
INSERT INTO tag_assignment (music_uuid, tag_name)
VALUES ($1, $2)
`

type AssignTagToMusicParams struct {
	MusicUuid pgtype.UUID
	TagName   string
}

func (q *Queries) AssignTagToMusic(ctx context.Context, arg AssignTagToMusicParams) error {
	_, err := q.db.Exec(ctx, assignTagToMusic, arg.MusicUuid, arg.TagName)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO music_tags (tag_name, tag_description)
VALUES ($1, $2)
`

type CreateTagParams struct {
	TagName        string
	TagDescription pgtype.Text
}

// ---- PUT
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.Exec(ctx, createTag, arg.TagName, arg.TagDescription)
	return err
}

const getAllTags = `-- name: GetAllTags :many
SELECT tag_name, tag_description, created_at FROM music_tags
ORDER BY tag_name
`

// ------------- Tags -----------------
// ---- GET
func (q *Queries) GetAllTags(ctx context.Context) ([]MusicTag, error) {
	rows, err := q.db.Query(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicTag
	for rows.Next() {
		var i MusicTag
		if err := rows.Scan(&i.TagName, &i.TagDescription, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMusicForTag = `-- name: GetMusicForTag :many
SELECT m.uuid, m.from_artist, m.uploaded_by, m.in_album, m.song_name, m.created_at, m.updated_at, m.path_in_file_storage, m.image_path, m.play_count, m.duration_seconds
FROM tag_assignment ta
JOIN music m
    ON ta.music_uuid = m.uuid
WHERE ta.tag_name = $1
`

func (q *Queries) GetMusicForTag(ctx context.Context, tagName string) ([]Music, error) {
	rows, err := q.db.Query(ctx, getMusicForTag, tagName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT tag_name, tag_description, created_at FROM music_tags
WHERE tag_name = $1
`

func (q *Queries) GetTag(ctx context.Context, tagName string) (MusicTag, error) {
	row := q.db.QueryRow(ctx, getTag, tagName)
	var i MusicTag
	err := row.Scan(&i.TagName, &i.TagDescription, &i.CreatedAt)
	return i, err
}

const getTagsForMusic = `-- name: GetTagsForMusic :many
SELECT mt.tag_name, mt.tag_description, mt.created_at
FROM tag_assignment ta
JOIN music_tags mt
    ON ta.tag_name = mt.tag_name
WHERE ta.music_uuid = $1
`

func (q *Queries) GetTagsForMusic(ctx context.Context, musicUuid pgtype.UUID) ([]MusicTag, error) {
	rows, err := q.db.Query(ctx, getTagsForMusic, musicUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicTag
	for rows.Next() {
		var i MusicTag
		if err := rows.Scan(&i.TagName, &i.TagDescription, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromMusic = `-- name: RemoveTagFromMusic :exec
DELETE FROM tag_assignment
WHERE music_uuid = $1 AND tag_name = $2
`

type RemoveTagFromMusicParams struct {
	MusicUuid pgtype.UUID
	TagName   string
}

// ---- DELETE
func (q *Queries) RemoveTagFromMusic(ctx context.Context, arg RemoveTagFromMusicParams) error {
	_, err := q.db.Exec(ctx, removeTagFromMusic, arg.MusicUuid, arg.TagName)
	return err
}
