// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 07_playlist.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :exec
INSERT INTO playlist_track (music_uuid, position, playlist_uuid)
VALUES ($1, $2, $3)
`

type AddTrackToPlaylistParams struct {
	MusicUuid    pgtype.UUID
	Position     int32
	PlaylistUuid pgtype.UUID
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addTrackToPlaylist, arg.MusicUuid, arg.Position, arg.PlaylistUuid)
	return err
}

const createPlaylist = `-- name: CreatePlaylist :exec
INSERT INTO playlist (from_user, original_name, description, is_public, image_path)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePlaylistParams struct {
	FromUser     pgtype.UUID
	OriginalName string
	Description  pgtype.Text
	IsPublic     pgtype.Bool
	ImagePath    pgtype.Text
}

// ---- PUT
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) error {
	_, err := q.db.Exec(ctx, createPlaylist,
		arg.FromUser,
		arg.OriginalName,
		arg.Description,
		arg.IsPublic,
		arg.ImagePath,
	)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlist
WHERE uuid = $2
AND is_user_allowed_playlist_edit($1, $2)
`

type DeletePlaylistParams struct {
	UserUuid pgtype.UUID
	Uuid     pgtype.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error {
	_, err := q.db.Exec(ctx, deletePlaylist, arg.UserUuid, arg.Uuid)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT uuid, from_user, original_name, description, is_public, image_path, created_at, updated_at FROM playlist
WHERE uuid = $1
`

// ------------- Playlist -----------------
// ---- GET
func (q *Queries) GetPlaylist(ctx context.Context, uuid pgtype.UUID) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylist, uuid)
	var i Playlist
	err := row.Scan(
		&i.Uuid,
		&i.FromUser,
		&i.OriginalName,
		&i.Description,
		&i.IsPublic,
		&i.ImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistTracks = `-- name: GetPlaylistTracks :many
SELECT m.uuid, m.from_artist, m.uploaded_by, m.in_album, m.song_name, m.created_at, m.updated_at, m.path_in_file_storage, m.image_path, m.play_count, m.duration_seconds
FROM playlist_track pt
JOIN music m
    ON pt.music_uuid = m.uuid
WHERE pt.playlist_uuid = $1
AND (
    $3::int IS NULL
    OR pt.position > $3
    )
ORDER BY pt.position
LIMIT $2
`

type GetPlaylistTracksParams struct {
	PlaylistUuid pgtype.UUID
	Limit        int32
	Column3      int32
}

func (q *Queries) GetPlaylistTracks(ctx context.Context, arg GetPlaylistTracksParams) ([]Music, error) {
	rows, err := q.db.Query(ctx, getPlaylistTracks, arg.PlaylistUuid, arg.Limit, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Music
	for rows.Next() {
		var i Music
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.UploadedBy,
			&i.InAlbum,
			&i.SongName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PathInFileStorage,
			&i.ImagePath,
			&i.PlayCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylists = `-- name: GetPlaylists :many
SELECT uuid, from_user, original_name, description, is_public, image_path, created_at, updated_at FROM playlist
WHERE (
    from_user = $1
    OR is_public = TRUE
)
AND (
    $3::timestamptz IS NULL
    OR (
        updated_at < $3
        OR (updated_at = $3 AND uuid < $4)
    )
)
ORDER BY updated_at DESC, uuid DESC
    LIMIT $2
`

type GetPlaylistsParams struct {
	FromUser pgtype.UUID
	Limit    int32
	Column3  pgtype.Timestamptz
	Uuid     pgtype.UUID
}

func (q *Queries) GetPlaylists(ctx context.Context, arg GetPlaylistsParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, getPlaylists,
		arg.FromUser,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.Uuid,
			&i.FromUser,
			&i.OriginalName,
			&i.Description,
			&i.IsPublic,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistsForUser = `-- name: GetPlaylistsForUser :many
SELECT uuid, from_user, original_name, description, is_public, image_path, created_at, updated_at FROM playlist
WHERE from_user = $1
AND (
    $3::timestamptz IS NULL
    OR (
        updated_at < $3
        OR (updated_at = $3 AND uuid < $4)
    )
)
ORDER BY updated_at DESC, uuid DESC
LIMIT $2
`

type GetPlaylistsForUserParams struct {
	FromUser pgtype.UUID
	Limit    int32
	Column3  pgtype.Timestamptz
	Uuid     pgtype.UUID
}

func (q *Queries) GetPlaylistsForUser(ctx context.Context, arg GetPlaylistsForUserParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, getPlaylistsForUser,
		arg.FromUser,
		arg.Limit,
		arg.Column3,
		arg.Uuid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.Uuid,
			&i.FromUser,
			&i.OriginalName,
			&i.Description,
			&i.IsPublic,
			&i.ImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromPlaylist = `-- name: RemoveTrackFromPlaylist :exec
DELETE FROM playlist_track
WHERE music_uuid = $3 AND playlist_uuid = $2
AND is_user_allowed_playlist_edit($1, $2)
`

type RemoveTrackFromPlaylistParams struct {
	UserUuid     pgtype.UUID
	PlaylistUuid pgtype.UUID
	MusicUuid    pgtype.UUID
}

// ---- DELETE
func (q *Queries) RemoveTrackFromPlaylist(ctx context.Context, arg RemoveTrackFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeTrackFromPlaylist, arg.UserUuid, arg.PlaylistUuid, arg.MusicUuid)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :exec
UPDATE playlist
SET original_name = $3,
    description = $4,
    is_public = $5
WHERE uuid = $2
AND is_user_allowed_playlist_edit($1, $2)
`

type UpdatePlaylistParams struct {
	UserUuid     pgtype.UUID
	Uuid         pgtype.UUID
	OriginalName string
	Description  pgtype.Text
	IsPublic     pgtype.Bool
}

// ---- POST
func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) error {
	_, err := q.db.Exec(ctx, updatePlaylist,
		arg.UserUuid,
		arg.Uuid,
		arg.OriginalName,
		arg.Description,
		arg.IsPublic,
	)
	return err
}

const updatePlaylistImage = `-- name: UpdatePlaylistImage :exec
UPDATE playlist
SET image_path = $3
WHERE uuid = $2
AND is_user_allowed_playlist_edit($1, $2)
`

type UpdatePlaylistImageParams struct {
	UserUuid  pgtype.UUID
	Uuid      pgtype.UUID
	ImagePath pgtype.Text
}

func (q *Queries) UpdatePlaylistImage(ctx context.Context, arg UpdatePlaylistImageParams) error {
	_, err := q.db.Exec(ctx, updatePlaylistImage, arg.UserUuid, arg.Uuid, arg.ImagePath)
	return err
}

const updateTrackPosition = `-- name: UpdateTrackPosition :exec
UPDATE playlist_track
SET position = $4
WHERE uuid = $3
AND is_user_allowed_playlist_edit($1, $2)
`

type UpdateTrackPositionParams struct {
	UserUuid     pgtype.UUID
	PlaylistUuid pgtype.UUID
	Uuid         pgtype.UUID
	Position     int32
}

func (q *Queries) UpdateTrackPosition(ctx context.Context, arg UpdateTrackPositionParams) error {
	_, err := q.db.Exec(ctx, updateTrackPosition,
		arg.UserUuid,
		arg.PlaylistUuid,
		arg.Uuid,
		arg.Position,
	)
	return err
}
