global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'music-streaming-monitor'

scrape_configs:
  - job_name: 'gateway-api'
    static_configs:
      - targets: ['gateway-api:8080']
        labels:
          service: 'gateway-api'
          environment: 'development'

  - job_name: 'service-user-database'
    static_configs:
      - targets: ['service-user-database:8080']
        labels:
          service: 'service-user-database'
          environment: 'development'

  - job_name: 'gateway-recommendation'
    static_configs:
      - targets: ['gateway-recommendation:8002']
        labels:
          service: 'gateway-recommendation'
          environment: 'development'

  - job_name: 'service-popularity'
    static_configs:
      - targets: ['service-popularity:8080']
        labels:
          service: 'service-popularity'
          environment: 'development'

  - job_name: 'service-bandit'
    static_configs:
      - targets: ['service-bandit:8001']
        labels:
          service: 'service-bandit'
          environment: 'development'

  - job_name: 'service-event-ingestion'
    static_configs:
      - targets: ['service-event-ingestion:8080']
        labels:
          service: 'service-event-ingestion'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          environment: 'development'
