// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 00_user.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, email, hashed_password, bio, profile_image_path)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	Username         string
	Email            string
	HashedPassword   string
	Bio              pgtype.Text
	ProfileImagePath pgtype.Text
}

// ---- PUT
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Bio,
		arg.ProfileImagePath,
	)
	return err
}

const getHashPassword = `-- name: GetHashPassword :one
SELECT hashed_password FROM users
WHERE uuid = $1
`

func (q *Queries) GetHashPassword(ctx context.Context, uuid pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHashPassword, uuid)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const getPublicUser = `-- name: GetPublicUser :one
SELECT uuid, username, email, bio, profile_image_path, created_at, updated_at FROM public_user
WHERE uuid = $1 LIMIT 1
`

// ------------- Users -----------------
// ---- GET
func (q *Queries) GetPublicUser(ctx context.Context, uuid pgtype.UUID) (PublicUser, error) {
	row := q.db.QueryRow(ctx, getPublicUser, uuid)
	var i PublicUser
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE users
SET email = $2
WHERE uuid = $1
`

type UpdateEmailParams struct {
	Uuid  pgtype.UUID
	Email string
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.Uuid, arg.Email)
	return err
}

const updateImage = `-- name: UpdateImage :exec
UPDATE users
SET profile_image_path = $2
WHERE uuid = $1
`

type UpdateImageParams struct {
	Uuid             pgtype.UUID
	ProfileImagePath pgtype.Text
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.Exec(ctx, updateImage, arg.Uuid, arg.ProfileImagePath)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET hashed_password = $2
WHERE uuid = $1
`

type UpdatePasswordParams struct {
	Uuid           pgtype.UUID
	HashedPassword string
}

// ---- POST
func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Uuid, arg.HashedPassword)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE users
SET username = $2,
    bio = $3
WHERE uuid = $1
`

type UpdateProfileParams struct {
	Uuid     pgtype.UUID
	Username string
	Bio      pgtype.Text
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile, arg.Uuid, arg.Username, arg.Bio)
	return err
}
