// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 08_listening_history.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListeningHistoryEntry = `-- name: AddListeningHistoryEntry :exec
INSERT INTO listening_history (user_uuid, music_uuid, listen_duration_seconds, completion_percentage)
VALUES ($1, $2, $3, $4)
`

type AddListeningHistoryEntryParams struct {
	UserUuid              pgtype.UUID
	MusicUuid             pgtype.UUID
	ListenDurationSeconds pgtype.Int4
	CompletionPercentage  pgtype.Numeric
}

// ---- PUT
func (q *Queries) AddListeningHistoryEntry(ctx context.Context, arg AddListeningHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, addListeningHistoryEntry,
		arg.UserUuid,
		arg.MusicUuid,
		arg.ListenDurationSeconds,
		arg.CompletionPercentage,
	)
	return err
}

const getListeningHistoryForUser = `-- name: GetListeningHistoryForUser :many
SELECT uuid, user_uuid, music_uuid, played_at, listen_duration_seconds, completion_percentage FROM listening_history
WHERE user_uuid = $1
ORDER BY played_at DESC
`

// ------------- ListeningHistory -----------------
// ---- GET
func (q *Queries) GetListeningHistoryForUser(ctx context.Context, userUuid pgtype.UUID) ([]ListeningHistory, error) {
	rows, err := q.db.Query(ctx, getListeningHistoryForUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListeningHistory
	for rows.Next() {
		var i ListeningHistory
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.MusicUuid,
			&i.PlayedAt,
			&i.ListenDurationSeconds,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyPlayedForUser = `-- name: GetRecentlyPlayedForUser :many
SELECT uuid, user_uuid, music_uuid, played_at, listen_duration_seconds, completion_percentage FROM listening_history
WHERE user_uuid = $1
ORDER BY played_at DESC
LIMIT $2
`

type GetRecentlyPlayedForUserParams struct {
	UserUuid pgtype.UUID
	Limit    int32
}

func (q *Queries) GetRecentlyPlayedForUser(ctx context.Context, arg GetRecentlyPlayedForUserParams) ([]ListeningHistory, error) {
	rows, err := q.db.Query(ctx, getRecentlyPlayedForUser, arg.UserUuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListeningHistory
	for rows.Next() {
		var i ListeningHistory
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.MusicUuid,
			&i.PlayedAt,
			&i.ListenDurationSeconds,
			&i.CompletionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMusicForUser = `-- name: GetTopMusicForUser :many
SELECT music_uuid, COUNT(*) as play_count
FROM listening_history
WHERE user_uuid = $1
GROUP BY music_uuid
ORDER BY COUNT(*) DESC
LIMIT $2
`

type GetTopMusicForUserParams struct {
	UserUuid pgtype.UUID
	Limit    int32
}

type GetTopMusicForUserRow struct {
	MusicUuid pgtype.UUID
	PlayCount int64
}

func (q *Queries) GetTopMusicForUser(ctx context.Context, arg GetTopMusicForUserParams) ([]GetTopMusicForUserRow, error) {
	rows, err := q.db.Query(ctx, getTopMusicForUser, arg.UserUuid, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMusicForUserRow
	for rows.Next() {
		var i GetTopMusicForUserRow
		if err := rows.Scan(&i.MusicUuid, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
