// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql_handler

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlbumsByNew = `-- name: GetAlbumsByNew :many
SELECT uuid, from_artist, original_name, description, created_at, updated_at FROM "Album"
ORDER BY created_at DESC
`

func (q *Queries) GetAlbumsByNew(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsByNew)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.Uuid,
			&i.FromArtist,
			&i.OriginalName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtists = `-- name: GetArtists :many
SELECT uuid, user_uuid, artist_name, bio, profile_image_path, created_at, updated_at FROM "Artist"
ORDER BY artist_name
`

func (q *Queries) GetArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.Uuid,
			&i.UserUuid,
			&i.ArtistName,
			&i.Bio,
			&i.ProfileImagePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT uuid, username, email, hashed_password, bio, profile_image_path, created_at, updated_at FROM "User"
WHERE UUID = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.ProfileImagePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE "User"
set hashed_password = $2
WHERE UUID = $1
`

type UpdatePasswordParams struct {
	Uuid           pgtype.UUID
	HashedPassword string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Uuid, arg.HashedPassword)
	return err
}
