name: Integration Tests

on:
  push:
  pull_request:


jobs:

  integration-tests-user-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start dependencies
        run: docker compose -f services/service_user_database/docker-compose.integration.yml up -d postgres-test minio-test vault-test mock-event-ingestion

      - name: Run init containers
        run: docker compose -f services/service_user_database/docker-compose.integration.yml up minio-init-test vault-init-test

      - name: Run integration tests
        run: docker compose -f services/service_user_database/docker-compose.integration.yml run --rm --no-deps integration-tests

      - name: Shutdown
        if: always()
        run: docker compose -f services/service_user_database/docker-compose.integration.yml down -v